### ISSUE TITLE
Online Demo error 

### ISSUE THREAD

**Issue by jaqif** [mit-han-lab/temporal-shift-module#55]
Installing everything on a nano with a jetson sd card image r32.2
when launching /onlinedemo/main.py on python3 here the raise error
CUDAError: Check failed: ret == 0 (-1 vs. 0) : cuModuleLoadData(&(module_[device_id]), data_.c_str()) failed with error: CUDA_ERROR_INVALID_PTX

cuda is my path

Thanks for helping

notice that 
1/ when making tvm, no /nnvm/python directory is generated.
2/ tried first to install on last release sd card image r32.3.1 and didn't succeed
=> on what version of jetson nano sd card you made it worked ?

**Comment by guojunyao419** [comment]
Encountered the exactly same error. 

"when making tvm, no /nnvm/python directory is generated." --Same problem occurred. Awaiting answers. Thanks!

**Comment by jaqif** [comment]
@guojunyao419 found out that current tvm v0.6 was release after the publication of online demo code.
Install v0.5 is resolving nnvm missing python dir.
This step is resolved but still can't succeed to launch online demo.

**Comment by guojunyao419** [comment]
@jaqif Thank you for your reply. Could you elaborate a bit on how you managed to install TVM v0.5? Thanks.

**Comment by guojunyao419** [comment]
@jaqif Thank you for your reply. I reinstalled tvm 0.5. However, another error occurred:
`Build Executor...
Traceback (most recent call last):
  File "main.py", line 386, in <module>
    main()
  File "main.py", line 282, in main
    executor, ctx = get_executor()
  File "main.py", line 96, in get_executor
    return torch2executor(torch_module, torch_inputs, target)
  File "main.py", line 49, in torch2executor
    tvm_module = tvm.module.load(lib_fname)
  File "/usr/local/lib/python3.6/dist-packages/tvm-0.5.dev0-py3.6-linux-aarch64.egg/tvm/module.py", line 244, in load
    return _LoadFromFile(path, fmt)
  File "tvm/_ffi/_cython/./function.pxi", line 286, in tvm._ffi._cy3.core.FunctionBase.__call__
  File "tvm/_ffi/_cython/./function.pxi", line 221, in tvm._ffi._cy3.core.FuncCall
  File "tvm/_ffi/_cython/./function.pxi", line 210, in tvm._ffi._cy3.core.FuncCall3
  File "tvm/_ffi/_cython/./base.pxi", line 143, in tvm._ffi._cy3.core.CALL
tvm._ffi.base.TVMError: [13:04:29] /home/lgsvl/incubator-tvm/src/runtime/module_util.cc:35: Check failed: f != nullptr Loader of _lib(module.loadbinary__lib) is not presented.
`
Have you encountered the same error?

**Comment by jaqif** [comment]
@guojunyao419 no I didn't, did you install the submodule before build tvm 0.5 ?
git submodule update --init

**Comment by jaqif** [comment]
@guojunyao419 did you succeed in installing and runing the online demo ?

**Comment by guojunyao419** [comment]
@jaqif  I installed tvm 0.5 and then had the error in my previous comment. I still haven't succeeded in running the demo due to that error.

**Comment by jaqif** [comment]
@guojunyao419 finally succeed after many many try.
Here is the solution
Build tvm v0.6 with submodule
git clone https://github.com/apache/incubator-tvm.git
cd incubator-tvm
git submodule update --init
then follow the next step in the online demo readme.
When you first launch main.py it should raise an error 
"ImportError: cannot import name 'bilinear_sample_nchw'
Regarding this : https://discuss.tvm.ai/t/cannot-import-name-bilinear-sample-nchw/2510/25
you have 2 solutions either add topi to lib path which should be  cleanest solution or copy the file  incubator-tvm/build/libtvm_topi.so to the tvm directory : usr/local/lib/python3.6/dist-packages/tvm-0.6.0-py3.6-linux-aarch64.egg/tvm/
Please let me know

**Comment by guojunyao419** [comment]
@jaqif Thank you so much! I reinstalled tvm v0.6 as you suggested, and now it works finally! Really appreciate it!

**Comment by tonylins** [comment]
@jaqif Glad to see you finally make it work! We are so sorry that the current tutorial cannot work directly. Would you like to help others and contribute to the repo by writing a pull request? Thanks!

**Comment by Ragavendrams** [comment]
@jaqif and @guojunyao419 : What version of Torch and Torchvision did you use?

**Comment by guojunyao419** [comment]
@Ragavendrams I used Pytorch 1.3.0 and torchvision 0.4.2.

**Comment by jaqif** [comment]
@Ragavendrams 
- torchvision 0.4.1
- pytorch 1.2.0

**Comment by Ragavendrams** [comment]
@jaqif : I used the same configuration as you but i still seem to be getting the error.
**TVMError: Check failed: f != nullptr: Loader of _lib(module.loadbinary__lib) is not presented.**

This is my configuration:
Package           Version
----------------- ---------------
attrs             19.3.0
Cython            0.29.15
decorator         4.4.1
numpy             1.18.1
onnx              1.6.0
Pillow            6.2.2
pip               20.0.2
pip-autoremove    0.9.1
protobuf          3.11.3
psutil            5.7.0
setuptools        45.2.0
six               1.14.0
topi              0.6.0
torch             1.2.0a0+8554416
torchvision       0.4.1a0+a263704
tvm               0.6.0
typing-extensions 3.7.4.1
wheel             0.34.2

do you have an idea as to what might be wrong?

**Comment by jaqif** [comment]
@Ragavendrams no idea, but it seems that you have the same problem as comment post by guojunyao419 some comment above (https://github.com/mit-han-lab/temporal-shift-module/issues/55#issuecomment-575800006) when using tvm 0.5.
may be you previously install tvm 0.5 and not remove it in the pip package directory.

**Comment by Karrthikpn** [comment]
When I ran python3.main.py I got a runtime error like "Runtime Error ( Unsupported: ONNX export of slice with dynamic inputs. DynamicSlice. please can anyone help me to resolve this issue..

thank you

**Comment by Ragavendrams** [comment]
@jaqif & @guojunyao419 : Can one of you please tell me how many vid/s you get running the demo on the Nano? I ran the demo on the TX2 using the GPU and can only get around 20 Vid/s, which is much lesser than what is mentioned. I guess this is because the author has not released the auto-tuning code.

Thanks a lot!

**Comment by guojunyao419** [comment]
@Ragavendrams On Jetson Nano, I get around 20 vid/s rate.

**Comment by Ragavendrams** [comment]
Thank you @guojunyao419

**Comment by tonylins** [comment]
Hi, I have updated the repo to use `onnx-simplifier` and some other minor changes. It should now eliminate the error. Feel free to reopen if the error persists. Thanks!
